/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Jun-2020 16:01:21 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

-- source C:/Users/Pc/Desktop/hamza1/Mat_Managem/management/New folder (3)/gestion1.sql
/* Drop Tables */





-- DROP TABLE IF EXISTS User 
-- ;

DROP DATABASE IF EXISTS laravel;
CREATE DATABASE laraveL;
USE laraveL;

DROP TABLE IF EXISTS EnseignantVacataire 
;

DROP TABLE IF EXISTS Materiel_info 
;

DROP TABLE IF EXISTS Forniture_info 
;

DROP TABLE IF EXISTS Equipement_bureau 
;

DROP TABLE IF EXISTS Materiel_acquisition 
;

DROP TABLE IF EXISTS Enseignant_materiel 
;

DROP TABLE IF EXISTS Enseignant_bureau 
;
DROP TABLE IF EXISTS Materiel 
;
DROP TABLE IF EXISTS Enseignant 
;
DROP TABLE IF EXISTS Person 
;
DROP TABLE IF EXISTS Reference 
;
DROP TABLE IF EXISTS Designation 
;

DROP TABLE IF EXISTS Bureau 
;


/* Create Tables */

CREATE TABLE Person
(
	active BOOL 	NOT NULL DEFAULT TRUE ,
	email VARCHAR(50) 	 NULL,
	nom VARCHAR(50) NOT	 NULL,
	prenom VARCHAR(50) NOT NULL,
	personID INT NOT NULL AUTO_INCREMENT,
	CONSTRAINT PK_Person PRIMARY KEY (personID)
)engine=innodb

;

CREATE TABLE Enseignant
(
	dateRecrutement DATE NOT  NULL,
	grade VARCHAR(50) NOT	 NULL,
	enseignantID INT NOT NULL,
	CONSTRAINT PK_Enseignant PRIMARY KEY (enseignantID)
)engine=innodb

;

-- CREATE TABLE User
-- (
-- 	PassWd VARCHAR(50) 	 NULL,
-- 	UserName VARCHAR(50) 	 NULL,
-- 	userID INT NOT NULL,
-- 	CONSTRAINT PK_User PRIMARY KEY (userID)
-- )

-- ;

CREATE TABLE EnseignantVacataire
(
	Etablisement VARCHAR(50) 	 NULL,
	grade VARCHAR(50) 	 NULL,
	numT VARCHAR(50) 	 NULL,
	dateDebut date	  NOT NULL,
	dateFin date   NOT NULL,
	enseignantVacataireID INT NOT NULL,
	CONSTRAINT PK_EnseignantVacataire PRIMARY KEY (enseignantVacataireID)
)engine=innodb

;

CREATE TABLE Designation
(
	designationID INT NOT NULL AUTO_INCREMENT,
	designation VARCHAR(50) NOT	 NULL,
	type int(1) NOT NULL,
	CONSTRAINT PK_Designation PRIMARY KEY (designationID)
)engine=innodb

;
CREATE TABLE Reference
(
	refID INT NOT NULL AUTO_INCREMENT,
	ref VARCHAR(50) NOT	 NULL,
	designationID  INT NOT NULL,
	CONSTRAINT PK_reference PRIMARY KEY (refID)
)engine=innodb

;

CREATE TABLE Materiel
(
	matID INT NOT NULL  AUTO_INCREMENT,
	designationID INT NOT NULL,
	active BOOL NOT	 NULL DEFAULT TRUE ,
	CONSTRAINT PK_Materiel PRIMARY KEY (matID)
)engine=innodb

;

CREATE TABLE Materiel_info
(
	matID INT NOT NULL,
	numInventaire int 	NOT NULL UNIQUE,
	commentaire TINYTEXT 	 NULL,
	refID INT NOT	 NULL,
	CONSTRAINT PK_MaterielInfo PRIMARY KEY (matID)
)engine=innodb

;

CREATE TABLE Forniture_info
(
	matID INT NOT NULL,
	commentaire TINYTEXT 	 NULL,
	refID INT NOT	 NULL,
	dateRestitution DATETIME ,
	CONSTRAINT PK_FornitureInfo PRIMARY KEY (matID)
)engine=innodb

;

CREATE TABLE Equipement_bureau
(
	numInventaire int NOT  NULL UNIQUE,
	matID INT NOT NULL,
	refID INT NOT	 NULL,
	dateRestitution DATETIME ,
	CONSTRAINT PK_EquipementBureau PRIMARY KEY (matID)
)engine=innodb

;

CREATE TABLE Materiel_acquisition
(
	matID INT NOT	 NULL,
	quantite int NOT	 NULL,
	dateAcquisition DATETIME NOT NULL,
	active BOOLEAN NOT NULL DEFAULT true,
	CONSTRAINT PK_MaterielAcquisition PRIMARY KEY (matID,quantite,dateAcquisition)
)engine=innodb

;

CREATE TABLE Enseignant_Materiel
(
	enseignantID INT NOT	 NULL,
	matID INT NOT	 NULL,
	quantite INT NOT NULL,
	date DATETIME NOT	 NULL,
	partage BOOLEAN NOT NULL DEFAULT FALSE,
	active BOOLEAN NOT NULL DEFAULT true,
	CONSTRAINT PK_EnseignantMateriel PRIMARY KEY (enseignantID,matID,date)
)engine=innodb

;


CREATE TABLE Bureau
(
	active BOOL NOT	 NULL DEFAULT TRUE,
	capacite int NOT	 NULL,
	dateAcquisition DATE NOT	 NULL,
	num VARCHAR(50) NOT	 NULL,
	CONSTRAINT PK_Bureau PRIMARY KEY (num)
)engine=innodb

;

CREATE TABLE Enseignant_bureau
(
	date DATETIME NOT	 NULL,
	bureauID VARCHAR(50) 	NOT NULL,
	enseignantID INT NOT	 NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT PK_EnsaignantBureau PRIMARY KEY (enseignantID,bureauID,date)
)engine=innodb

;

/* Create Foreign Key Constraints */

ALTER TABLE Enseignant 
 ADD CONSTRAINT FK_Enseignant_Person
	FOREIGN KEY (enseignantID) REFERENCES Person (personID) ON DELETE No Action ON UPDATE No Action
;

-- ALTER TABLE User 
--  ADD CONSTRAINT FK_User_Enseignant
-- 	FOREIGN KEY (userID) REFERENCES Enseignant (enseignantID) ON DELETE No Action ON UPDATE No Action
-- ;

ALTER TABLE EnseignantVacataire 
 ADD CONSTRAINT FK_EnseignantVacataire_Person
	FOREIGN KEY (enseignantVacataireID) REFERENCES Person (personID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Materiel 
 ADD CONSTRAINT FK_Materiel_Designation
	FOREIGN KEY (designationID) REFERENCES Designation (designationID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Materiel_info 
 ADD CONSTRAINT FK_MatereilInfo_Materiel
	FOREIGN KEY (matID) REFERENCES Materiel (matID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Materiel_info 
 ADD CONSTRAINT FK_MatereilInfo_Reference
	FOREIGN KEY (refID) REFERENCES Reference (refID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Forniture_info 
 ADD CONSTRAINT FK_FornitureInfo_Reference
	FOREIGN KEY (refID) REFERENCES Reference (refID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Forniture_info 
 ADD CONSTRAINT FK_FornitureInfo_Materiel
	FOREIGN KEY (matID) REFERENCES Materiel (matID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Equipement_bureau 
 ADD CONSTRAINT FK_EquipementBureau_Reference
	FOREIGN KEY (refID) REFERENCES Reference (refID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Equipement_bureau 
 ADD CONSTRAINT FK_EquipementBureau_Materiel
	FOREIGN KEY (matID) REFERENCES Materiel (matID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Materiel_acquisition 
 ADD CONSTRAINT FK_MaterielAcquisition_Materiel
	FOREIGN KEY (matID) REFERENCES Materiel (matID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Enseignant_materiel 
 ADD CONSTRAINT FK_EnseignantMateriel_Enseignant
	FOREIGN KEY (enseignantID) REFERENCES Enseignant (enseignantID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Enseignant_materiel 
 ADD CONSTRAINT FK_EnseignantMateriel_Materiel
	FOREIGN KEY (matID) REFERENCES Materiel (matID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Enseignant_bureau 
 ADD CONSTRAINT FK_EnsaignantBureau_Bureau
	FOREIGN KEY (bureauID) REFERENCES Bureau (num) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Enseignant_bureau 
 ADD CONSTRAINT FK_EnsaignantBureau_Enseignant
	FOREIGN KEY (enseignantID) REFERENCES Enseignant (enseignantID) ON DELETE No Action ON UPDATE No Action
;
ALTER TABLE Designation 
 ADD CONSTRAINT UK_designation UNIQUE (designation,type)
;
ALTER TABLE Reference 
 ADD CONSTRAINT FK_reference_designation
	FOREIGN KEY (designationID) REFERENCES designation (designationID) ON DELETE No Action ON UPDATE No Action
;
